# For running app + dependencies like Postgres, Rabbitmq ,Redis
# Define services for app, db,

# TODO: Race condition resolution the rabbitmq server starts on port don't accept the conections for some time,
# But server tries for the connection hence causing it to crash
# So later add a retry logic for few attempts with 5 sec delay assuming it will eventually connect
# For now i wil add the restart condition in the docker compose file itself, the restart condition


# TODO: changed ports mapping since conflict with local servers. To be rolled back.
#       5673->5672
#       15673->15672
#       5435->5432

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    ports:
      - "5673:5672"
      - "15673:15672" # for the ui
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: this_is_mjk 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compass
    ports:
      - "5435:5432"
    # in health check change the user (i have set it to the value above)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U this_is_mjk -d compass"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: container/Dockerfile
    # it will restart the container if it crashers (due to rabbit mq or any other issue)
    restart: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      # force Go to use go.mod/go.sum for dependency management
      GO111MODULE: on
